# Generated by Django 5.2.4 on 2025-08-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_seller", models.BooleanField(default=False)),
                ("is_buyer", models.BooleanField(default=True)),
                ("mfa_secret", models.CharField(blank=True, max_length=16, null=True)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="full name"),
                ),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="myapp_users",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="myapp_user_permissions",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
