# Generated by Django 5.2.4 on 2025-08-28 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_brand_categorys_manufactureyear_trim_user_is_buyer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("excerpt", models.TextField(blank=True, editable=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("author", models.CharField(default="Anonymous", max_length=100)),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("tags", models.ManyToManyField(blank=True, to="myapp.tag")),
            ],
        ),
    ]
