# Generated by Django 5.2.4 on 2025-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
