# Generated by Django 5.2.4 on 2025-08-28 15:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_article_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DriveTerrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EngineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FuelOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="exchange_option",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default=False, max_length=3
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image10",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image2",
            field=models.ImageField(default="vehicles/bus2.png", upload_to="vehicles/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image3",
            field=models.ImageField(default="vehicles/bus2.png", upload_to="vehicles/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image4",
            field=models.ImageField(default="vehicles/bus2.png", upload_to="vehicles/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image5",
            field=models.ImageField(default="vehicles/bus2.png", upload_to="vehicles/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image6",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image7",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image8",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image9",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="negotiable",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="vehicles/bus2.png",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="no_of_tyres",
            field=models.PositiveIntegerField(
                default=4, validators=[django.core.validators.MaxValueValidator(32)]
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="registered",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="vehicles/bus2.png",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="seat",
            field=models.PositiveIntegerField(
                default=5, validators=[django.core.validators.MaxValueValidator(80)]
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="social_media",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trim",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.color",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.condition",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="drive_terrain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.driveterrain",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="engine_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.enginetype",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.fueloption",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.state",
            ),
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.state"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="town",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="myapp.town"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vas",
            field=models.ManyToManyField(to="myapp.vas"),
        ),
    ]
