# Generated by Django 5.2.4 on 2025-08-28 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_color_condition_driveterrain_enginetype_fueloption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="date_sold",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="horsepower",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(200)],
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="index",
            field=models.CharField(
                blank=True, db_index=True, max_length=130, unique=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="number_cylinder",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="number_of_view",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="transmission",
            field=models.CharField(
                choices=[("automatic", "Automatic"), ("manual", "Manual")],
                default="automatic",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
