# Generated by Django 5.2.4 on 2025-08-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_brand_logo_vehicle1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(default="ayo", upload_to="vehicles/logo"),
            preserve_default=False,
        ),
    ]
