# Generated by Django 5.2.4 on 2025-08-31 13:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("myapp", "0013_alter_user_groups_alter_user_user_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InnerColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
        migrations.CreateModel(
            name="DealerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_logo",
                    models.ImageField(blank=True, null=True, upload_to="dealer_logos/"),
                ),
                ("business_address", models.CharField(max_length=255)),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.state",
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.town",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="inner_color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.innercolor",
            ),
        ),
        migrations.CreateModel(
            name="Vehicle2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange_option",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "registered",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "negotiable",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "no_of_tyres",
                    models.PositiveIntegerField(
                        default=4,
                        validators=[django.core.validators.MaxValueValidator(32)],
                    ),
                ),
                (
                    "seat",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(80)],
                    ),
                ),
                ("mileage", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transmission",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        default="automatic",
                        max_length=10,
                    ),
                ),
                (
                    "number_cylinder",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                (
                    "horsepower",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(200)],
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField()),
                ("social_media", models.URLField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="vehicles/")),
                ("image2", models.ImageField(upload_to="vehicles/")),
                ("image3", models.ImageField(upload_to="vehicles/")),
                ("image4", models.ImageField(upload_to="vehicles/")),
                ("image5", models.ImageField(upload_to="vehicles/")),
                (
                    "image6",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                (
                    "image7",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                (
                    "image8",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                (
                    "image9",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                (
                    "image10",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_sold", models.DateTimeField(blank=True, null=True)),
                ("number_of_view", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("vin", models.CharField(blank=True, max_length=50)),
                (
                    "index",
                    models.CharField(
                        blank=True, db_index=True, max_length=130, unique=True
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.category",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.color",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.condition",
                    ),
                ),
                (
                    "drive_terrain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.driveterrain",
                    ),
                ),
                (
                    "engine_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.enginetype",
                    ),
                ),
                (
                    "fuel_option",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.fueloption",
                    ),
                ),
                (
                    "manufacture_year",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.manufactureyear",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.state",
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.town",
                    ),
                ),
                (
                    "trim",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.trim",
                    ),
                ),
                ("vas", models.ManyToManyField(to="myapp.vas")),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.vehiclemodel",
                    ),
                ),
            ],
        ),
    ]
