# Generated by Django 5.2.4 on 2025-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_alter_vas_options_color_hex_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
