# Generated by Django 5.2.4 on 2025-09-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_alter_vehiclemodel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle2",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="category",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="color",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="drive_terrain",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="engine_type",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="fuel_option",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="manufacture_year",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="state",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="town",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="trim",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="vas",
        ),
        migrations.RemoveField(
            model_name="vehicle2",
            name="vehicle_model",
        ),
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="color",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="condition",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="driveterrain",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="enginetype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="fueloption",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="innercolor",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="manufactureyear",
            options={"ordering": ["year"]},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="town",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="trim",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vas",
            options={
                "ordering": ["name"],
                "verbose_name": "Value Added Service",
                "verbose_name_plural": "Value Added Services",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="vehiclemodel",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="trim",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100, null=tuple),
        ),
        migrations.DeleteModel(
            name="Vehicle1",
        ),
        migrations.DeleteModel(
            name="Vehicle2",
        ),
    ]
